# Generated by Django 5.1.3 on 2025-01-04 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_alter_appointments_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Diagnosis',
            new_name='MedicalRecord',
        ),
    ]
