# Generated by Django 5.1.3 on 2025-01-05 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_rename_diagnosis_medicalrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescriptions',
            name='patient_id',
        ),
        migrations.RemoveField(
            model_name='prescriptions',
            name='staff_id',
        ),
        migrations.AlterField(
            model_name='departments',
            name='doctor',
            field=models.ManyToManyField(related_name='location', to='hospital.doctor'),
        ),
    ]
