# Generated by Django 5.1.3 on 2025-01-06 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_alter_appointments_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departments',
            name='location',
        ),
        migrations.AddField(
            model_name='departments',
            name='location_name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='departments',
            name='doctor',
            field=models.ManyToManyField(related_name='departments', to='hospital.doctor'),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
