# Generated by Django 5.1.3 on 2025-01-06 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_remove_departments_doctor_departments_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='location_name',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
