# Generated by Django 5.1.3 on 2025-01-06 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0010_alter_departments_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='ward',
            name='ward_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
