# Generated by Django 5.1.3 on 2025-01-06 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0011_ward_ward_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='billings',
            name='doctor_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='billings', to='hospital.doctor'),
            preserve_default=False,
        ),
    ]
